### ISSUE TITLE
lsd_slam RAM problem

### ISSUE THREAD

**Issue by axelfar** [Hypha-ROS/hypharos_ardrone_navigation#2]
Hello,
Thanks for this project.
I have a little problem when I use lsd_slam with the drone camera.
The memory allocation increase, after a moment the computer crash. 
I didn't change your code or the lsd_slam code. It's could be the "ImageBuffer" ? 

I take some screen-shots about that.
When I run  "rosrun lsd_slam_core live_slam image:=/ardrone/front/image_raw _lib:=src/lsd_slam/lsd_slam_core/calib/ardrone_calibration.cfg"

![lsd_slam1](https://user-images.githubusercontent.com/34505045/39929691-ffbe56d2-5538-11e8-94c4-e2b44cf96ec4.png)

After few seconds:
![lsd_slam2](https://user-images.githubusercontent.com/34505045/39929693-ffe56e3e-5538-11e8-9254-5e13246c6269.png)

Best regards,

**Comment by jim1993** [comment]
Hi @axelfar 
Please refer to #1 , I guess they are the same issue.

**Comment by axelfar** [comment]
I think it's different, for me the lsd_slam works,  i don't have "core dumped".
I have a good image resolution (640x352).
My memory problem happen during the process.

**Comment by axelfar** [comment]
I delete and re-create my workspace and that is works. 
thanks!
