### ISSUE TITLE
AR.Drone camera calibration for lsd_slam

### ISSUE THREAD

**Issue by axelfar** [Hypha-ROS/hypharos_ardrone_navigation#5]
Hello,
I try many times to calibrate my drone with 'camera_calibration' node. But when I commit the result and use lsd_slam I have a bad result  like this: 
![screenshot from 2018-05-15 15 38 10](https://user-images.githubusercontent.com/34505045/40162178-5f3f5c4a-59b3-11e8-8d44-c30bb0f08867.png)
 
If you have a good result with your drone I just want your tips for a good calibration.
 
It's could be the resolution ? Because my calibration view is like that : 
![screenshot from 2018-05-17 09 15 14](https://user-images.githubusercontent.com/34505045/40162230-9363b52a-59b3-11e8-94b3-c7993acbb563.png)

My calibration file : 

image_width: 640
image_height: 352
camera_name: ardrone_front
camera_matrix:
  rows: 3
  cols: 3
  data: [570.9902683884858, 0, 328.956626996734, 0, 569.8251065587548, 178.5418664651152, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.5647011921497734, 0.3479795365150913, -0.0008891926813252254, 0.002831456909685551, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [461.0075073242188, 0, 334.950547214743, 0, 0, 535.9346313476562, 178.169361178092, 0, 0, 0, 1, 0]

**Comment by kungfrank** [comment]
Hi~ 
Please check whether your LSDslam node subscribe correct image topic(image after calibrate).
It might be similar to "/ardrone/front/image_rect". By the way, you can also use rqt_image_viewer to see the image topic : )

**Comment by axelfar** [comment]
Yes it's better with image_rect! 

You know how change the voxel's size with octomap? Because i have to much voxels and my computer has blow up. I try to change the 'resolution' value in  /ar_drone_moveit/launch/octomap.launch  but nothing change :(
